package org.seguro.model;

// Generated 11-ago-2015 18:28:13 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aseguradora generated by hbm2java
 */
@Entity
@Table(name = "aseguradora"
      , schema = "public")
public class Aseguradora implements java.io.Serializable
{

   private int idAseguradora;
   private String nombreCorto;
   private String nombreLargo;
   private String logo;
   private String emailResponsable;
   private Integer nitSuc;
   private Date fechaInicioOperaciones;
   private Date fechaFinOperaciones;
   private String nombreResponsable;
   private Integer telefonoResponsable;
   private String direccionLegal;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<Usuario> usuarios = new HashSet<Usuario>(0);

   public Aseguradora()
   {
   }

   public Aseguradora(int idAseguradora, String nombreCorto, String nombreLargo)
   {
      this.idAseguradora = idAseguradora;
      this.nombreCorto = nombreCorto;
      this.nombreLargo = nombreLargo;
   }

   public Aseguradora(int idAseguradora, String nombreCorto, String nombreLargo, String logo, String emailResponsable, Integer nitSuc, Date fechaInicioOperaciones, Date fechaFinOperaciones, String nombreResponsable, Integer telefonoResponsable, String direccionLegal, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Usuario> usuarios)
   {
      this.idAseguradora = idAseguradora;
      this.nombreCorto = nombreCorto;
      this.nombreLargo = nombreLargo;
      this.logo = logo;
      this.emailResponsable = emailResponsable;
      this.nitSuc = nitSuc;
      this.fechaInicioOperaciones = fechaInicioOperaciones;
      this.fechaFinOperaciones = fechaFinOperaciones;
      this.nombreResponsable = nombreResponsable;
      this.telefonoResponsable = telefonoResponsable;
      this.direccionLegal = direccionLegal;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.usuarios = usuarios;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_aseguradora", unique = true, nullable = false, insertable=false)
   public int getIdAseguradora()
   {
      return this.idAseguradora;
   }

   public void setIdAseguradora(int idAseguradora)
   {
      this.idAseguradora = idAseguradora;
   }

   @Column(name = "nombre_corto", nullable = false, length = 50)
   public String getNombreCorto()
   {
      return this.nombreCorto;
   }

   public void setNombreCorto(String nombreCorto)
   {
      this.nombreCorto = nombreCorto;
   }

   @Column(name = "nombre_largo", nullable = false, length = 200)
   public String getNombreLargo()
   {
      return this.nombreLargo;
   }

   public void setNombreLargo(String nombreLargo)
   {
      this.nombreLargo = nombreLargo;
   }

   @Column(name = "logo", length = 100)
   public String getLogo()
   {
      return this.logo;
   }

   public void setLogo(String logo)
   {
      this.logo = logo;
   }

   @Column(name = "email_responsable", length = 50)
   public String getEmailResponsable()
   {
      return this.emailResponsable;
   }

   public void setEmailResponsable(String emailResponsable)
   {
      this.emailResponsable = emailResponsable;
   }

   @Column(name = "nit_suc")
   public Integer getNitSuc()
   {
      return this.nitSuc;
   }

   public void setNitSuc(Integer nitSuc)
   {
      this.nitSuc = nitSuc;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_inicio_operaciones", length = 29)
   public Date getFechaInicioOperaciones()
   {
      return this.fechaInicioOperaciones;
   }

   public void setFechaInicioOperaciones(Date fechaInicioOperaciones)
   {
      this.fechaInicioOperaciones = fechaInicioOperaciones;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_fin_operaciones", length = 29)
   public Date getFechaFinOperaciones()
   {
      return this.fechaFinOperaciones;
   }

   public void setFechaFinOperaciones(Date fechaFinOperaciones)
   {
      this.fechaFinOperaciones = fechaFinOperaciones;
   }

   @Column(name = "nombre_responsable", length = 100)
   public String getNombreResponsable()
   {
      return this.nombreResponsable;
   }

   public void setNombreResponsable(String nombreResponsable)
   {
      this.nombreResponsable = nombreResponsable;
   }

   @Column(name = "telefono_responsable")
   public Integer getTelefonoResponsable()
   {
      return this.telefonoResponsable;
   }

   public void setTelefonoResponsable(Integer telefonoResponsable)
   {
      this.telefonoResponsable = telefonoResponsable;
   }

   @Column(name = "direccion_legal", length = 200)
   public String getDireccionLegal()
   {
      return this.direccionLegal;
   }

   public void setDireccionLegal(String direccionLegal)
   {
      this.direccionLegal = direccionLegal;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "aseguradora")
   public Set<Usuario> getUsuarios()
   {
      return this.usuarios;
   }

   public void setUsuarios(Set<Usuario> usuarios)
   {
      this.usuarios = usuarios;
   }

}
