package org.seguro.model;

// Generated 11-ago-2015 18:28:13 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CoberturaSiniestro generated by hbm2java
 */
@Entity
@Table(name = "cobertura_siniestro"
      , schema = "public")
public class CoberturaSiniestro implements java.io.Serializable
{

   private int idCoberturaSiniestro;
   private Condicion condicion;
   private Siniestro siniestro;
   private Double valorAsegurado;
   private Double valorIndemnizado;
   private String documentos;
   private Date fechaSolicitud;
   private Date fechaEntrega;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;

   public CoberturaSiniestro()
   {
   }

   public CoberturaSiniestro(int idCoberturaSiniestro)
   {
      this.idCoberturaSiniestro = idCoberturaSiniestro;
   }

   public CoberturaSiniestro(int idCoberturaSiniestro, Condicion condicion, Siniestro siniestro, Double valorAsegurado, Double valorIndemnizado, String documentos, Date fechaSolicitud, Date fechaEntrega, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado)
   {
      this.idCoberturaSiniestro = idCoberturaSiniestro;
      this.condicion = condicion;
      this.siniestro = siniestro;
      this.valorAsegurado = valorAsegurado;
      this.valorIndemnizado = valorIndemnizado;
      this.documentos = documentos;
      this.fechaSolicitud = fechaSolicitud;
      this.fechaEntrega = fechaEntrega;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
   }

   @Id
   @Column(name = "id_cobertura_siniestro", unique = true, nullable = false)
   public int getIdCoberturaSiniestro()
   {
      return this.idCoberturaSiniestro;
   }

   public void setIdCoberturaSiniestro(int idCoberturaSiniestro)
   {
      this.idCoberturaSiniestro = idCoberturaSiniestro;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_condicion")
   public Condicion getCondicion()
   {
      return this.condicion;
   }

   public void setCondicion(Condicion condicion)
   {
      this.condicion = condicion;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_siniestro")
   public Siniestro getSiniestro()
   {
      return this.siniestro;
   }

   public void setSiniestro(Siniestro siniestro)
   {
      this.siniestro = siniestro;
   }

   @Column(name = "valor_asegurado", precision = 17, scale = 17)
   public Double getValorAsegurado()
   {
      return this.valorAsegurado;
   }

   public void setValorAsegurado(Double valorAsegurado)
   {
      this.valorAsegurado = valorAsegurado;
   }

   @Column(name = "valor_indemnizado", precision = 17, scale = 17)
   public Double getValorIndemnizado()
   {
      return this.valorIndemnizado;
   }

   public void setValorIndemnizado(Double valorIndemnizado)
   {
      this.valorIndemnizado = valorIndemnizado;
   }

   @Column(name = "documentos", length = 30)
   public String getDocumentos()
   {
      return this.documentos;
   }

   public void setDocumentos(String documentos)
   {
      this.documentos = documentos;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_solicitud", length = 29)
   public Date getFechaSolicitud()
   {
      return this.fechaSolicitud;
   }

   public void setFechaSolicitud(Date fechaSolicitud)
   {
      this.fechaSolicitud = fechaSolicitud;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_entrega", length = 29)
   public Date getFechaEntrega()
   {
      return this.fechaEntrega;
   }

   public void setFechaEntrega(Date fechaEntrega)
   {
      this.fechaEntrega = fechaEntrega;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

}
