package org.seguro.model;

// Generated 11-ago-2015 18:28:13 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compania generated by hbm2java
 */
@Entity
@Table(name = "compania"
      , schema = "public")
public class Compania implements java.io.Serializable
{

   private int idCompania;
   private String nombre;
   private String acronimo;
   private String logo;
   private String mail;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<Prima> primas = new HashSet<Prima>(0);
   private Set<Tasa> tasas = new HashSet<Tasa>(0);

   public Compania()
   {
   }

   public Compania(int idCompania)
   {
      this.idCompania = idCompania;
   }

   public Compania(int idCompania, String nombre, String acronimo, String logo, String mail, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Prima> primas, Set<Tasa> tasas)
   {
      this.idCompania = idCompania;
      this.nombre = nombre;
      this.acronimo = acronimo;
      this.logo = logo;
      this.mail = mail;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.primas = primas;
      this.tasas = tasas;
   }

   @Id
   @Column(name = "id_compania", unique = true, nullable = false)
   public int getIdCompania()
   {
      return this.idCompania;
   }

   public void setIdCompania(int idCompania)
   {
      this.idCompania = idCompania;
   }

   @Column(name = "nombre", length = 50)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "acronimo", length = 50)
   public String getAcronimo()
   {
      return this.acronimo;
   }

   public void setAcronimo(String acronimo)
   {
      this.acronimo = acronimo;
   }

   @Column(name = "logo", length = 50)
   public String getLogo()
   {
      return this.logo;
   }

   public void setLogo(String logo)
   {
      this.logo = logo;
   }

   @Column(name = "mail", length = 50)
   public String getMail()
   {
      return this.mail;
   }

   public void setMail(String mail)
   {
      this.mail = mail;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Prima> getPrimas()
   {
      return this.primas;
   }

   public void setPrimas(Set<Prima> primas)
   {
      this.primas = primas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Tasa> getTasas()
   {
      return this.tasas;
   }

   public void setTasas(Set<Tasa> tasas)
   {
      this.tasas = tasas;
   }

}
