package org.seguro.model;

// Generated 11-ago-2015 18:28:13 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Condicion generated by hbm2java
 */
@Entity
@Table(name = "condicion"
      , schema = "public")
public class Condicion implements java.io.Serializable
{

   private int idCondicion;
   private String nombre;
   private String acronimo;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<DetalleTasaCondicion> detalleTasaCondicions = new HashSet<DetalleTasaCondicion>(0);
   private Set<CoberturaSiniestro> coberturaSiniestros = new HashSet<CoberturaSiniestro>(0);

   public Condicion()
   {
   }

   public Condicion(int idCondicion)
   {
      this.idCondicion = idCondicion;
   }

   public Condicion(int idCondicion, String nombre, String acronimo, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<DetalleTasaCondicion> detalleTasaCondicions, Set<CoberturaSiniestro> coberturaSiniestros)
   {
      this.idCondicion = idCondicion;
      this.nombre = nombre;
      this.acronimo = acronimo;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.detalleTasaCondicions = detalleTasaCondicions;
      this.coberturaSiniestros = coberturaSiniestros;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_condicion", unique = true, nullable = false, insertable=false)
   public int getIdCondicion()
   {
      return this.idCondicion;
   }

   public void setIdCondicion(int idCondicion)
   {
      this.idCondicion = idCondicion;
   }

   @Column(name = "nombre", length = 250)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "acronimo", length = 500)
   public String getAcronimo()
   {
      return this.acronimo;
   }

   public void setAcronimo(String acronimo)
   {
      this.acronimo = acronimo;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "condicion")
   public Set<DetalleTasaCondicion> getDetalleTasaCondicions()
   {
      return this.detalleTasaCondicions;
   }

   public void setDetalleTasaCondicions(Set<DetalleTasaCondicion> detalleTasaCondicions)
   {
      this.detalleTasaCondicions = detalleTasaCondicions;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "condicion")
   public Set<CoberturaSiniestro> getCoberturaSiniestros()
   {
      return this.coberturaSiniestros;
   }

   public void setCoberturaSiniestros(Set<CoberturaSiniestro> coberturaSiniestros)
   {
      this.coberturaSiniestros = coberturaSiniestros;
   }

}
