package org.seguro.model;

// Generated 11-ago-2015 18:28:13 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Poliza generated by hbm2java
 */
@Entity
@Table(name = "poliza"
      , schema = "public")
public class Poliza implements java.io.Serializable
{

   private int idPoliza;
   private Automotor automotor;
   private Cliente cliente;
   private Tasa tasa;
   private Integer nroCotizacion;
   private String codigoBarra;
   private Date inicioVigencia;
   private Date finVigencia;
   private Date fechaContrato;
   private String contratado;
   private BigDecimal valorAsegurado;
   private Boolean estadoCotizacion;
   private BigDecimal primaContratada;
   private Integer nroPoliza;
   private Integer nroContrato;
   private String origen;
   private Boolean estadoNuevo;
   private Boolean estadoRenovacion;
   private Boolean credito;
   private Boolean subrogado;
   private Boolean registrado;
   private BigDecimal valorSubrogacion;
   private Integer mes;
   private Integer dia;
   private Integer ano;
   private Boolean general;
   private String observaciones;
   private String notas;
   private String publico;
   private String codigoVehiculo;
   private String tipoPago;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<PlanPago> planPagos = new HashSet<PlanPago>(0);
   private Set<PolizaCobertura> polizaCoberturas = new HashSet<PolizaCobertura>(0);
   private Set<Prima> primas = new HashSet<Prima>(0);
   private Set<PolizaDocumento> polizaDocumentos = new HashSet<PolizaDocumento>(0);
   private Set<Siniestro> siniestros = new HashSet<Siniestro>(0);
   private Set<PolizaFoto> polizaFotos = new HashSet<PolizaFoto>(0);

   public Poliza()
   {
   }

   public Poliza(int idPoliza)
   {
      this.idPoliza = idPoliza;
   }

   public Poliza(int idPoliza, Automotor automotor, Cliente cliente, Tasa tasa, Integer nroCotizacion, String codigoBarra, Date inicioVigencia, Date finVigencia, Date fechaContrato, String contratado, BigDecimal valorAsegurado, Boolean estadoCotizacion, BigDecimal primaContratada, Integer nroPoliza, Integer nroContrato, String origen, Boolean estadoNuevo, Boolean estadoRenovacion, Boolean credito, Boolean subrogado, Boolean registrado, BigDecimal valorSubrogacion, Integer mes, Integer dia, Integer ano, Boolean general, String observaciones, String notas, String publico, String codigoVehiculo, String tipoPago, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<PlanPago> planPagos,
         Set<PolizaCobertura> polizaCoberturas, Set<Prima> primas, Set<PolizaDocumento> polizaDocumentos, Set<Siniestro> siniestros, Set<PolizaFoto> polizaFotos)
   {
      this.idPoliza = idPoliza;
      this.automotor = automotor;
      this.cliente = cliente;
      this.tasa = tasa;
      this.nroCotizacion = nroCotizacion;
      this.codigoBarra = codigoBarra;
      this.inicioVigencia = inicioVigencia;
      this.finVigencia = finVigencia;
      this.fechaContrato = fechaContrato;
      this.contratado = contratado;
      this.valorAsegurado = valorAsegurado;
      this.estadoCotizacion = estadoCotizacion;
      this.primaContratada = primaContratada;
      this.nroPoliza = nroPoliza;
      this.nroContrato = nroContrato;
      this.origen = origen;
      this.estadoNuevo = estadoNuevo;
      this.estadoRenovacion = estadoRenovacion;
      this.credito = credito;
      this.subrogado = subrogado;
      this.registrado = registrado;
      this.valorSubrogacion = valorSubrogacion;
      this.mes = mes;
      this.dia = dia;
      this.ano = ano;
      this.general = general;
      this.observaciones = observaciones;
      this.notas = notas;
      this.publico = publico;
      this.codigoVehiculo = codigoVehiculo;
      this.tipoPago = tipoPago;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.planPagos = planPagos;
      this.polizaCoberturas = polizaCoberturas;
      this.primas = primas;
      this.polizaDocumentos = polizaDocumentos;
      this.siniestros = siniestros;
      this.polizaFotos = polizaFotos;
   }

   @Id
   @Column(name = "id_poliza", unique = true, nullable = false)
   public int getIdPoliza()
   {
      return this.idPoliza;
   }

   public void setIdPoliza(int idPoliza)
   {
      this.idPoliza = idPoliza;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_automotor")
   public Automotor getAutomotor()
   {
      return this.automotor;
   }

   public void setAutomotor(Automotor automotor)
   {
      this.automotor = automotor;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cliente")
   public Cliente getCliente()
   {
      return this.cliente;
   }

   public void setCliente(Cliente cliente)
   {
      this.cliente = cliente;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_tasa")
   public Tasa getTasa()
   {
      return this.tasa;
   }

   public void setTasa(Tasa tasa)
   {
      this.tasa = tasa;
   }

   @Column(name = "nro_cotizacion")
   public Integer getNroCotizacion()
   {
      return this.nroCotizacion;
   }

   public void setNroCotizacion(Integer nroCotizacion)
   {
      this.nroCotizacion = nroCotizacion;
   }

   @Column(name = "codigo_barra", length = 50)
   public String getCodigoBarra()
   {
      return this.codigoBarra;
   }

   public void setCodigoBarra(String codigoBarra)
   {
      this.codigoBarra = codigoBarra;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "inicio_vigencia", length = 29)
   public Date getInicioVigencia()
   {
      return this.inicioVigencia;
   }

   public void setInicioVigencia(Date inicioVigencia)
   {
      this.inicioVigencia = inicioVigencia;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fin_vigencia", length = 29)
   public Date getFinVigencia()
   {
      return this.finVigencia;
   }

   public void setFinVigencia(Date finVigencia)
   {
      this.finVigencia = finVigencia;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_contrato", length = 29)
   public Date getFechaContrato()
   {
      return this.fechaContrato;
   }

   public void setFechaContrato(Date fechaContrato)
   {
      this.fechaContrato = fechaContrato;
   }

   @Column(name = "contratado", length = 50)
   public String getContratado()
   {
      return this.contratado;
   }

   public void setContratado(String contratado)
   {
      this.contratado = contratado;
   }

   @Column(name = "valor_asegurado", precision = 18)
   public BigDecimal getValorAsegurado()
   {
      return this.valorAsegurado;
   }

   public void setValorAsegurado(BigDecimal valorAsegurado)
   {
      this.valorAsegurado = valorAsegurado;
   }

   @Column(name = "estado_cotizacion")
   public Boolean getEstadoCotizacion()
   {
      return this.estadoCotizacion;
   }

   public void setEstadoCotizacion(Boolean estadoCotizacion)
   {
      this.estadoCotizacion = estadoCotizacion;
   }

   @Column(name = "prima_contratada", precision = 18)
   public BigDecimal getPrimaContratada()
   {
      return this.primaContratada;
   }

   public void setPrimaContratada(BigDecimal primaContratada)
   {
      this.primaContratada = primaContratada;
   }

   @Column(name = "nro_poliza")
   public Integer getNroPoliza()
   {
      return this.nroPoliza;
   }

   public void setNroPoliza(Integer nroPoliza)
   {
      this.nroPoliza = nroPoliza;
   }

   @Column(name = "nro_contrato")
   public Integer getNroContrato()
   {
      return this.nroContrato;
   }

   public void setNroContrato(Integer nroContrato)
   {
      this.nroContrato = nroContrato;
   }

   @Column(name = "origen", length = 50)
   public String getOrigen()
   {
      return this.origen;
   }

   public void setOrigen(String origen)
   {
      this.origen = origen;
   }

   @Column(name = "estado_nuevo")
   public Boolean getEstadoNuevo()
   {
      return this.estadoNuevo;
   }

   public void setEstadoNuevo(Boolean estadoNuevo)
   {
      this.estadoNuevo = estadoNuevo;
   }

   @Column(name = "estado_renovacion")
   public Boolean getEstadoRenovacion()
   {
      return this.estadoRenovacion;
   }

   public void setEstadoRenovacion(Boolean estadoRenovacion)
   {
      this.estadoRenovacion = estadoRenovacion;
   }

   @Column(name = "credito")
   public Boolean getCredito()
   {
      return this.credito;
   }

   public void setCredito(Boolean credito)
   {
      this.credito = credito;
   }

   @Column(name = "subrogado")
   public Boolean getSubrogado()
   {
      return this.subrogado;
   }

   public void setSubrogado(Boolean subrogado)
   {
      this.subrogado = subrogado;
   }

   @Column(name = "registrado")
   public Boolean getRegistrado()
   {
      return this.registrado;
   }

   public void setRegistrado(Boolean registrado)
   {
      this.registrado = registrado;
   }

   @Column(name = "valor_subrogacion", precision = 18)
   public BigDecimal getValorSubrogacion()
   {
      return this.valorSubrogacion;
   }

   public void setValorSubrogacion(BigDecimal valorSubrogacion)
   {
      this.valorSubrogacion = valorSubrogacion;
   }

   @Column(name = "mes")
   public Integer getMes()
   {
      return this.mes;
   }

   public void setMes(Integer mes)
   {
      this.mes = mes;
   }

   @Column(name = "dia")
   public Integer getDia()
   {
      return this.dia;
   }

   public void setDia(Integer dia)
   {
      this.dia = dia;
   }

   @Column(name = "ano")
   public Integer getAno()
   {
      return this.ano;
   }

   public void setAno(Integer ano)
   {
      this.ano = ano;
   }

   @Column(name = "general")
   public Boolean getGeneral()
   {
      return this.general;
   }

   public void setGeneral(Boolean general)
   {
      this.general = general;
   }

   @Column(name = "observaciones", length = 500)
   public String getObservaciones()
   {
      return this.observaciones;
   }

   public void setObservaciones(String observaciones)
   {
      this.observaciones = observaciones;
   }

   @Column(name = "notas", length = 500)
   public String getNotas()
   {
      return this.notas;
   }

   public void setNotas(String notas)
   {
      this.notas = notas;
   }

   @Column(name = "publico", length = 100)
   public String getPublico()
   {
      return this.publico;
   }

   public void setPublico(String publico)
   {
      this.publico = publico;
   }

   @Column(name = "codigo_vehiculo", length = 50)
   public String getCodigoVehiculo()
   {
      return this.codigoVehiculo;
   }

   public void setCodigoVehiculo(String codigoVehiculo)
   {
      this.codigoVehiculo = codigoVehiculo;
   }

   @Column(name = "tipo_pago", length = 50)
   public String getTipoPago()
   {
      return this.tipoPago;
   }

   public void setTipoPago(String tipoPago)
   {
      this.tipoPago = tipoPago;
   }

   @Column(name = "flag_estado", length = 20)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "poliza")
   public Set<PlanPago> getPlanPagos()
   {
      return this.planPagos;
   }

   public void setPlanPagos(Set<PlanPago> planPagos)
   {
      this.planPagos = planPagos;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "poliza")
   public Set<PolizaCobertura> getPolizaCoberturas()
   {
      return this.polizaCoberturas;
   }

   public void setPolizaCoberturas(Set<PolizaCobertura> polizaCoberturas)
   {
      this.polizaCoberturas = polizaCoberturas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "poliza")
   public Set<Prima> getPrimas()
   {
      return this.primas;
   }

   public void setPrimas(Set<Prima> primas)
   {
      this.primas = primas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "poliza")
   public Set<PolizaDocumento> getPolizaDocumentos()
   {
      return this.polizaDocumentos;
   }

   public void setPolizaDocumentos(Set<PolizaDocumento> polizaDocumentos)
   {
      this.polizaDocumentos = polizaDocumentos;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "poliza")
   public Set<Siniestro> getSiniestros()
   {
      return this.siniestros;
   }

   public void setSiniestros(Set<Siniestro> siniestros)
   {
      this.siniestros = siniestros;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "poliza")
   public Set<PolizaFoto> getPolizaFotos()
   {
      return this.polizaFotos;
   }

   public void setPolizaFotos(Set<PolizaFoto> polizaFotos)
   {
      this.polizaFotos = polizaFotos;
   }

}
