package org.seguro.model;

// Generated 11-ago-2015 18:28:13 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolizaDocumento generated by hbm2java
 */
@Entity
@Table(name = "poliza_documento"
      , schema = "public")
public class PolizaDocumento implements java.io.Serializable
{

   private int idPolizaDocumento;
   private Poliza poliza;
   private String carnet;
   private String rua;
   private String otros;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;

   public PolizaDocumento()
   {
   }

   public PolizaDocumento(int idPolizaDocumento)
   {
      this.idPolizaDocumento = idPolizaDocumento;
   }

   public PolizaDocumento(int idPolizaDocumento, Poliza poliza, String carnet, String rua, String otros, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado)
   {
      this.idPolizaDocumento = idPolizaDocumento;
      this.poliza = poliza;
      this.carnet = carnet;
      this.rua = rua;
      this.otros = otros;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
   }

   @Id
   @Column(name = "id_poliza_documento", unique = true, nullable = false)
   public int getIdPolizaDocumento()
   {
      return this.idPolizaDocumento;
   }

   public void setIdPolizaDocumento(int idPolizaDocumento)
   {
      this.idPolizaDocumento = idPolizaDocumento;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_poliza")
   public Poliza getPoliza()
   {
      return this.poliza;
   }

   public void setPoliza(Poliza poliza)
   {
      this.poliza = poliza;
   }

   @Column(name = "carnet", length = 200)
   public String getCarnet()
   {
      return this.carnet;
   }

   public void setCarnet(String carnet)
   {
      this.carnet = carnet;
   }

   @Column(name = "rua", length = 200)
   public String getRua()
   {
      return this.rua;
   }

   public void setRua(String rua)
   {
      this.rua = rua;
   }

   @Column(name = "otros", length = 200)
   public String getOtros()
   {
      return this.otros;
   }

   public void setOtros(String otros)
   {
      this.otros = otros;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

}
