package org.seguro.model;

// Generated 11-ago-2015 18:28:13 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prima generated by hbm2java
 */
@Entity
@Table(name = "prima"
      , schema = "public")
public class Prima implements java.io.Serializable
{

   private int idPrima;
   private Compania compania;
   private Poliza poliza;
   private BigDecimal primaContado;
   private BigDecimal primaCredito;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;

   public Prima()
   {
   }

   public Prima(int idPrima)
   {
      this.idPrima = idPrima;
   }

   public Prima(int idPrima, Compania compania, Poliza poliza, BigDecimal primaContado, BigDecimal primaCredito, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado)
   {
      this.idPrima = idPrima;
      this.compania = compania;
      this.poliza = poliza;
      this.primaContado = primaContado;
      this.primaCredito = primaCredito;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
   }

   @Id
   @Column(name = "id_prima", unique = true, nullable = false)
   public int getIdPrima()
   {
      return this.idPrima;
   }

   public void setIdPrima(int idPrima)
   {
      this.idPrima = idPrima;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_compania")
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_poliza")
   public Poliza getPoliza()
   {
      return this.poliza;
   }

   public void setPoliza(Poliza poliza)
   {
      this.poliza = poliza;
   }

   @Column(name = "prima_contado", precision = 18)
   public BigDecimal getPrimaContado()
   {
      return this.primaContado;
   }

   public void setPrimaContado(BigDecimal primaContado)
   {
      this.primaContado = primaContado;
   }

   @Column(name = "prima_credito", precision = 18)
   public BigDecimal getPrimaCredito()
   {
      return this.primaCredito;
   }

   public void setPrimaCredito(BigDecimal primaCredito)
   {
      this.primaCredito = primaCredito;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

}
