package org.seguro.model;

// Generated 11-ago-2015 18:28:13 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Siniestro generated by hbm2java
 */
@Entity
@Table(name = "siniestro"
      , schema = "public")
public class Siniestro implements java.io.Serializable
{

   private int idSiniestro;
   private Poliza poliza;
   private String nombreCliente;
   private String direccion;
   private Integer telefono;
   private Date fechaSinistro;
   private String autoridadIntervino;
   private Double montoReclamado;
   private Double montoIndemnizado;
   private Double franquicia;
   private String flagEstado;
   private String breveNarracion;
   private Integer nroPoliza;
   private String lugar;
   private Integer numeroCaso;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<SiniestroDocumento> siniestroDocumentos = new HashSet<SiniestroDocumento>(0);
   private Set<RestauracionMecanica> restauracionMecanicas = new HashSet<RestauracionMecanica>(0);
   private Set<CoberturaSiniestro> coberturaSiniestros = new HashSet<CoberturaSiniestro>(0);
   private Set<RecuperacionMedica> recuperacionMedicas = new HashSet<RecuperacionMedica>(0);
   private Set<SiniestroFoto> siniestroFotos = new HashSet<SiniestroFoto>(0);

   public Siniestro()
   {
   }

   public Siniestro(int idSiniestro)
   {
      this.idSiniestro = idSiniestro;
   }

   public Siniestro(int idSiniestro, Poliza poliza, String nombreCliente, String direccion, Integer telefono, Date fechaSinistro, String autoridadIntervino, Double montoReclamado, Double montoIndemnizado, Double franquicia, String flagEstado, String breveNarracion, Integer nroPoliza, String lugar, Integer numeroCaso, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<SiniestroDocumento> siniestroDocumentos, Set<RestauracionMecanica> restauracionMecanicas, Set<CoberturaSiniestro> coberturaSiniestros, Set<RecuperacionMedica> recuperacionMedicas, Set<SiniestroFoto> siniestroFotos)
   {
      this.idSiniestro = idSiniestro;
      this.poliza = poliza;
      this.nombreCliente = nombreCliente;
      this.direccion = direccion;
      this.telefono = telefono;
      this.fechaSinistro = fechaSinistro;
      this.autoridadIntervino = autoridadIntervino;
      this.montoReclamado = montoReclamado;
      this.montoIndemnizado = montoIndemnizado;
      this.franquicia = franquicia;
      this.flagEstado = flagEstado;
      this.breveNarracion = breveNarracion;
      this.nroPoliza = nroPoliza;
      this.lugar = lugar;
      this.numeroCaso = numeroCaso;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.siniestroDocumentos = siniestroDocumentos;
      this.restauracionMecanicas = restauracionMecanicas;
      this.coberturaSiniestros = coberturaSiniestros;
      this.recuperacionMedicas = recuperacionMedicas;
      this.siniestroFotos = siniestroFotos;
   }

   @Id
   @Column(name = "id_siniestro", unique = true, nullable = false)
   public int getIdSiniestro()
   {
      return this.idSiniestro;
   }

   public void setIdSiniestro(int idSiniestro)
   {
      this.idSiniestro = idSiniestro;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_poliza")
   public Poliza getPoliza()
   {
      return this.poliza;
   }

   public void setPoliza(Poliza poliza)
   {
      this.poliza = poliza;
   }

   @Column(name = "nombre_cliente", length = 90)
   public String getNombreCliente()
   {
      return this.nombreCliente;
   }

   public void setNombreCliente(String nombreCliente)
   {
      this.nombreCliente = nombreCliente;
   }

   @Column(name = "direccion", length = 200)
   public String getDireccion()
   {
      return this.direccion;
   }

   public void setDireccion(String direccion)
   {
      this.direccion = direccion;
   }

   @Column(name = "telefono")
   public Integer getTelefono()
   {
      return this.telefono;
   }

   public void setTelefono(Integer telefono)
   {
      this.telefono = telefono;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_sinistro", length = 29)
   public Date getFechaSinistro()
   {
      return this.fechaSinistro;
   }

   public void setFechaSinistro(Date fechaSinistro)
   {
      this.fechaSinistro = fechaSinistro;
   }

   @Column(name = "autoridad_intervino", length = 90)
   public String getAutoridadIntervino()
   {
      return this.autoridadIntervino;
   }

   public void setAutoridadIntervino(String autoridadIntervino)
   {
      this.autoridadIntervino = autoridadIntervino;
   }

   @Column(name = "monto_reclamado", precision = 17, scale = 17)
   public Double getMontoReclamado()
   {
      return this.montoReclamado;
   }

   public void setMontoReclamado(Double montoReclamado)
   {
      this.montoReclamado = montoReclamado;
   }

   @Column(name = "monto_indemnizado", precision = 17, scale = 17)
   public Double getMontoIndemnizado()
   {
      return this.montoIndemnizado;
   }

   public void setMontoIndemnizado(Double montoIndemnizado)
   {
      this.montoIndemnizado = montoIndemnizado;
   }

   @Column(name = "franquicia", precision = 17, scale = 17)
   public Double getFranquicia()
   {
      return this.franquicia;
   }

   public void setFranquicia(Double franquicia)
   {
      this.franquicia = franquicia;
   }

   @Column(name = "flag_estado", length = 10)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Column(name = "breve_narracion", length = 500)
   public String getBreveNarracion()
   {
      return this.breveNarracion;
   }

   public void setBreveNarracion(String breveNarracion)
   {
      this.breveNarracion = breveNarracion;
   }

   @Column(name = "nro_poliza")
   public Integer getNroPoliza()
   {
      return this.nroPoliza;
   }

   public void setNroPoliza(Integer nroPoliza)
   {
      this.nroPoliza = nroPoliza;
   }

   @Column(name = "lugar", length = 30)
   public String getLugar()
   {
      return this.lugar;
   }

   public void setLugar(String lugar)
   {
      this.lugar = lugar;
   }

   @Column(name = "numero_caso")
   public Integer getNumeroCaso()
   {
      return this.numeroCaso;
   }

   public void setNumeroCaso(Integer numeroCaso)
   {
      this.numeroCaso = numeroCaso;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "siniestro")
   public Set<SiniestroDocumento> getSiniestroDocumentos()
   {
      return this.siniestroDocumentos;
   }

   public void setSiniestroDocumentos(Set<SiniestroDocumento> siniestroDocumentos)
   {
      this.siniestroDocumentos = siniestroDocumentos;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "siniestro")
   public Set<RestauracionMecanica> getRestauracionMecanicas()
   {
      return this.restauracionMecanicas;
   }

   public void setRestauracionMecanicas(Set<RestauracionMecanica> restauracionMecanicas)
   {
      this.restauracionMecanicas = restauracionMecanicas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "siniestro")
   public Set<CoberturaSiniestro> getCoberturaSiniestros()
   {
      return this.coberturaSiniestros;
   }

   public void setCoberturaSiniestros(Set<CoberturaSiniestro> coberturaSiniestros)
   {
      this.coberturaSiniestros = coberturaSiniestros;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "siniestro")
   public Set<RecuperacionMedica> getRecuperacionMedicas()
   {
      return this.recuperacionMedicas;
   }

   public void setRecuperacionMedicas(Set<RecuperacionMedica> recuperacionMedicas)
   {
      this.recuperacionMedicas = recuperacionMedicas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "siniestro")
   public Set<SiniestroFoto> getSiniestroFotos()
   {
      return this.siniestroFotos;
   }

   public void setSiniestroFotos(Set<SiniestroFoto> siniestroFotos)
   {
      this.siniestroFotos = siniestroFotos;
   }

}
