package org.seguro.model;

// Generated 11-ago-2015 18:28:13 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario"
      , schema = "public")
public class Usuario implements java.io.Serializable
{

   private int idUsuario;
   private Aseguradora aseguradora;
   private String nombreCompleto;
   private String usuarioLogin;
   private String usuarioPassword;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);

   public Usuario()
   {
   }

   public Usuario(int idUsuario, Aseguradora aseguradora, String usuarioLogin, String usuarioPassword)
   {
      this.idUsuario = idUsuario;
      this.aseguradora = aseguradora;
      this.usuarioLogin = usuarioLogin;
      this.usuarioPassword = usuarioPassword;
   }

   public Usuario(int idUsuario, Aseguradora aseguradora, String nombreCompleto, String usuarioLogin, String usuarioPassword, String flagEstado, Date fechaReg, String usuarioReg, Set<UsuarioRol> usuarioRols)
   {
      this.idUsuario = idUsuario;
      this.aseguradora = aseguradora;
      this.nombreCompleto = nombreCompleto;
      this.usuarioLogin = usuarioLogin;
      this.usuarioPassword = usuarioPassword;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.usuarioRols = usuarioRols;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_usuario", unique = true, nullable = false, insertable=false)
   public int getIdUsuario()
   {
      return this.idUsuario;
   }

   public void setIdUsuario(int idUsuario)
   {
      this.idUsuario = idUsuario;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_aseguradora", nullable = false)
   public Aseguradora getAseguradora()
   {
      return this.aseguradora;
   }

   public void setAseguradora(Aseguradora aseguradora)
   {
      this.aseguradora = aseguradora;
   }

   @Column(name = "nombre_completo", length = 50)
   public String getNombreCompleto()
   {
      return this.nombreCompleto;
   }

   public void setNombreCompleto(String nombreCompleto)
   {
      this.nombreCompleto = nombreCompleto;
   }

   @Column(name = "usuario_login", nullable = false, length = 30)
   public String getUsuarioLogin()
   {
      return this.usuarioLogin;
   }

   public void setUsuarioLogin(String usuarioLogin)
   {
      this.usuarioLogin = usuarioLogin;
   }

   @Column(name = "usuario_password", nullable = false, length = 100)
   public String getUsuarioPassword()
   {
      return this.usuarioPassword;
   }

   public void setUsuarioPassword(String usuarioPassword)
   {
      this.usuarioPassword = usuarioPassword;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
   public Set<UsuarioRol> getUsuarioRols()
   {
      return this.usuarioRols;
   }

   public void setUsuarioRols(Set<UsuarioRol> usuarioRols)
   {
      this.usuarioRols = usuarioRols;
   }

}
